version: "3.9"

services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
